### ISSUE TITLE
Bug when writing debug files during a model run

### ISSUE THREAD

**Issue by tpilz** [echse/echse_generic#1]
When creating debug files (*.dbg) for a specific object during a model run the value of variables of type 'inputSim' is always a hexadecimal number which, I presume, is a reference and not the actual value of the variable. When setting a variable of type 'output' equal to the value of the variable of type 'inputSim' there is a reasonable value. I guess there must be a bug wen writing the debug files.

This error can be reproduced with any model engine, any class and any object that contains variables of type 'inputSim'.

**Comment by echse** [comment]
Indeed, an address was printed instead of the value. Has been fixed in the latest revision uploaded just now.
